# Generated by Django 4.0.4 on 2022-05-16 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_userfollowing_unique_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='images/assets/default_image.png', upload_to='images/profile_images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
