# Generated by Django 4.0.4 on 2022-05-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_user_user_img_alter_userfollowing_from_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp_created']},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='postlike',
            name='timestamp',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unqiue_likes'),
        ),
    ]
