# Generated by Django 4.0.4 on 2022-05-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image_file',
        ),
        migrations.CreateModel(
            name='Auction_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_item', to='auctions.auction')),
            ],
        ),
    ]
