# Generated by Django 4.0.4 on 2022-05-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_image_auction_item_auction_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='images',
        ),
        migrations.AddField(
            model_name='auction_image',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auction'),
        ),
    ]
