# Generated by Django 4.0.4 on 2022-05-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_images_auction_image_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.auction')),
            ],
        ),
        migrations.DeleteModel(
            name='Auction_Image',
        ),
    ]
