# Generated by Django 4.0.4 on 2022-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_description_alter_auction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='condition',
            field=models.CharField(choices=[('BN', 'Brand new'), ('PT', 'Pristine'), ('SU', 'Slighty used'), ('OD', 'Old')], max_length=20, null=True),
        ),
    ]
