# Generated by Django 4.0.4 on 2022-05-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
