# Generated by Django 4.0.4 on 2022-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auction_liked_user_comment_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('CR', 'Cars'), ('CT', 'Computers & Tech'), ('PT', 'Pets'), ('FD', 'Food & Drinks'), ('FS', 'Fashion'), ('TY', 'Toys'), ('HM', 'Home')], max_length=20, null=True),
        ),
    ]
