# Generated by Django 4.0.4 on 2022-05-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_user_profile_image_alter_auction_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-date_created']},
        ),
    ]
